Develop
gvs-rs/pubnub-c-core pull request #28
Opened 2019-10-13 16:20 UTC by Petar-Saric

resolving issue: Штоперица стане после 24 дана #27.

2019-10-13 20:15 UTC, sveljko requested changes

2019-10-13 20:15 UTC, sveljko commented on posix/msstopwatch_monotonic_clock.c
> +    if (0 == monotonic_clock_get_time(&(ts))) {
не требају ти заграде око `тс`

2019-10-13 20:15 UTC, sveljko commented on posix/pbmc_elapsed_ms.h
> +struct timespec;
Ово "декларисање унапред" не може да ради (исправно) ако се користи "права" структура, већ само ако се користи показивач (јер величина показивача не зависи од величине структуре). Дакле, овде или треба да укључи заглавље у коме се `струцт тимеспец` налази, или да се у `пбмс_елапсед_мс()` користи `струцт тимеспец*`. Предлажем ово прво, јер је `тимеспец`  довољно мали да није проблем да се пренесе по вредности,
а то је брже од показивача јер нема "преусмеравања".

2019-10-13 20:15 UTC, sveljko commented on windows/msstopwatch_windows.c
> +    psw->t_ref = 0;
разумем зашто овако, али, чињеница је да сада постоји, врло мала додуше, али, ипак постоји шанса да ово не ради како треба - ако ГетТицкЦоунт64() врати `0`. Стога, у `пбмс_старт` треба "добуџити" да, ако се баш то и деси, заменити `0` са `1` и пријавити `ПУБНУБ_ЛОГ_ЊАРНИНГ()`. Биће ружно што онда сва трајања, која почињу на `0`, буду за "тик краћа", али, то је "мање зло" него да пукне `АССЕРТ` у `пбмс_старт()`.

2019-10-13 20:15 UTC, sveljko commented on posix/pbmc_elapsed_ms.h
> +int pbmc_elapsed_ms(struct timespec prev_timspec, struct timespec timspec);
хм, а шта му дође префикс `пбмц`?

2019-10-13 21:14 UTC, Petar-Saric commented on posix/pbmc_elapsed_ms.h
> +int pbmc_elapsed_ms(struct timespec prev_timspec, struct timespec timspec);
pubnub_monotonic_clock

2019-10-14 08:57 UTC, sveljko commented on posix/pbmc_elapsed_ms.h
> +int pbmc_elapsed_ms(struct timespec prev_timspec, struct timespec timspec);
Разумем, али, одвећ је слично са `пбмс`, нека буде `пбтимеспец_елапсед_мс` - јер и нема везе са "монотоним часовником", већ са било која два `тимеспец`-а (који могу да се добију са било каквог часовника).

2019-10-14 14:35 UTC, merged