Develop
gvs-rs/pubnub-c-core pull request #31
Opened 2019-10-17 15:51 UTC by Petar-Saric

actions API adjustments.

2019-10-18 22:06 UTC, sveljko requested changes

2019-10-18 22:06 UTC, sveljko commented on core/pbcc_actions_api.c
> +    snprintf(action_tt_str,
ово је мало шашаво, копирамо без паметног разлога. Треба направити нови `АППЕНД` макро, који прима ниску и дужину "колико да дода", па га онда искористити овде

2019-10-18 22:06 UTC, sveljko commented on core/pbcc_actions_api.c
> +    APPEND_URL_ENCODED_M(pb, action_tt_str);
ТТ нема потребе да се УРЛ енкодирају

2019-10-18 22:06 UTC, sveljko commented on core/pubnub_memory_block.h
> +/** Returns memory block for a given NULL terminated string */
треба напоменути да не заузима или копира ишта, већ да `птр` резултата буде `= стр`

2019-10-19 10:49 UTC, Petar-Saric commented on core/pbcc_actions_api.c
> +    APPEND_URL_ENCODED_M(pb, action_tt_str);
Taj makro je mogao da se iskoristi pa sam njega stavio.

2019-10-19 13:40 UTC, sveljko requested changes

2019-10-19 13:40 UTC, sveljko commented on core/pubnub_ccore_pubsub.h
> +        if ((pbc)->http_buf_len + (size) > sizeof (pbc)->http_buf) {           \
Овде се одвећ много појављује `(пбц)`. Сем што код ружније изгледа, то значи и да се овај параметар макроа много пута "рачуна", па може да буде чудних последица ако се не проследи "чист" показивач, већ неки израз чији је резултат показивач.

Урадити уобичајени трик са помоћном променљивом:
```
    пубнуб_т* М_пбп_ = (пбц);
    //// надаље употребљавамо М_пбп_ уместо `(пбц`)
```
Овде је згодно што већ имамо блок за `иф ((стринг) != НУЛЛ)`.

Овде се и `стринг` и `сизе` рачунају више пута, па, кад се већ овим бавимо, није лоше да и њих овако "обрадимо". У ту сврху направи "вештачки" блок уз помоћ `до њхиле(0)` "петље" и ту деклариши ове помоћне променљиве.

Кад већ чистимо, дај мало мање "преоптерећена" имена овим параметрима од `стринг` и `сизе`. Уобичајени `с` и `н` су сасвим ОК, али, ако ти се не свиђају, можеш и нешто друго.

2019-10-19 13:40 UTC, sveljko commented on core/pubnub_memory_block.h
> +/** Returns memory block for a given NULL terminated string.
није `НУЛЛ` завршен, већ `НУЛ` завршен. `НУЛЛ` је Ц показивач на "ништа" (који је у пракси `(воид*)0`, али не мора да буде _баш_ то), а `НУЛ` (са једним `Л`) је АСЦИИ симбол за "знак који није знак" а чија је бројевна вредност износи `0`.

2019-10-19 17:02 UTC, sveljko approved these changes

2019-10-19 17:03 UTC, merged