Develop
gvs-rs/pubnub-c-core pull request #33
Opened 2019-11-06 10:29 UTC by Petar-Saric

resolving issue: Тупко #29 - callback_posix.

2019-11-07 12:00 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +#define pubnub_is_auto_hertbeat_enabled(pb) false
Врло занимљиво, обрати пажњу, сва четири имају погрешно записано `хеарт` и то на три различита начина! :)

2019-11-07 12:48 UTC, sveljko requested changes

2019-11-07 12:48 UTC, sveljko commented on core/pubnub_ccore_limits.h
> +#if !defined PUBNUB_MIN_TRANSACTION_TIMER
Нема потребе за овим `#иф`, ово корисник не може да подешава

2019-11-07 12:48 UTC, sveljko commented on core/pubnub_ccore_limits.h
> +/** Mininmal duration of the transaction timer, in milliseconds. You
минимал (не треба ти `н`)

2019-11-07 12:48 UTC, sveljko commented on core/pubnub_coreapi.c
> +static void update_list(char** list, const char* leave_list)
Име функције је непотребно уопштено. Ажурирање може да значи све и свашта, а ова функција, колико ја видим, само избацује канале са `леаве_лист` из `лист`.

2019-11-07 12:48 UTC, sveljko commented on core/pubnub_coreapi.c
> +    for (ll_start = leave_list; ll_start < ll_end;) {
Ова функција је веома сложена и тешка за анализу. Треба је поједноставити тако што позива помоћну функцију која избацује један канал из листе, а овде је онда позивати за један по један канал из `леаве_лист`.

2019-11-07 12:48 UTC, sveljko commented on core/pubnub_pubsubapi.c
> +//
што овде и мало навише још стоје "празни коментари"?

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    int active_timers pubnub_guarded_by(timerlock);
а што ово није `сизе_т`?

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    int thumper_index;
У складу са разговором, ово личи да може да се избаци и да се злоупотреби индекс из самог контекста

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +#define TAKE_TIMER_OUT(active_timers)           \
ово је сувише сложено за макро, нека буде обична (статичка) функција

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +            pthread_mutex_destroy(&m_watcher.stoplock);
Хм, да, видиш, ово одавно хоћу да средим и за "изворну" сокет-вочер нит. Дакле, безвезе је да се ова сложена иницијализација нити ради у овој функцији и онда мора да води рачуна који све "андраци" из претходног дела функције треба да се ослобађају (уништавају) ако дође до неке грешке успут. На пример, ако претходни део функције (пре `#иф`) буде промењен тако да прави још неки андрак, онда то треба додати овде на више места, што се лако "испусти".

Уместо тога, ово одрадити у помоћној функцији, која онда ослобађа-уништава само оно што и сама прави. Овде само проверити резултат који та помоћна функција врати и, ако је неуспех, онда ослободити-уништити то што треба, што се онда ради само на једном месту (као и у `#елсе` грани).

Засад, то промени само овде, после можемо  и "сокет-вочер" нит да ажурирамо у том смислу.

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        thumper->period_sec = PUBNUB_MIN_TRANSACTION_TIMER / UNIT_IN_MILLI;
хм, а што овде "дираш" `период_сец`?

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    release_thumper((int)(pb->autoRegister.thumperIndex));
чему овде кастовање? зашто `тхумберИндеџ` није `сизе_т`? Или, обратно, зашто `реласе_тхумпер` не прима `инт`?

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +void pbauto_heartbeat_free_register(pubnub_t* pb)
ово је мало чудно име... `регистер` обично значи "региструј се". Дакле, овом "регистру" треба дати неког боље име. Рецимо `инфо` или тако нешто (немој контекст, то користимо за Пубнуб контекст).

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +int pbauto_heartbeat_form_channels_and_ch_groups(pubnub_t* pb,
ова функција је чудна... ако су оба параметра "показивачи на НУЛЛ" онда се нешто уписује у њих из контекста. Ако неки јесте, онда се _из_ њега уписује _у контекст_, при томе, ако овај други јесте показивач на НУЛЛ, у исти се _не_ преписује ништа из контекста. Прилично је збуњујуће чему би то све заједно могло да служи...

Сасвим могуће да то има неког смисла, али је врло шашаво имати такву функцију кад је гледаш "саму за себе". Треба је поделити на две - једна која преписује "на једну" и друга која преписује "на другу страну", па позивати по потреби.

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +            return -1;
Хм, овде враћамо грешку, али не ослобађамо меморију заузету за канал... претпостављам да ће неко на крају да је ослободи, али, из угла ове функције, логично је претпоставити да враћање грешке значи да онај ко позива неће даље ништа да ради (уосталом, то је и правилно, неко се претплатио и на канал и на групу и нема смисла да "тупкамо" само по каналу). Ако је тако, онда нема потребе да "држимо" (заузетом) меморију која се неће да користи, односно, онда је овде треба "одмах" ослободити.

Сем тога, ако се ради о грешци, онда треба `ПУБНУБ_ЛОГ_ЕРРОР`.

2019-11-07 12:48 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    int thumper_index = (int)(pb->autoRegister.thumperIndex);
овде се поставља питање "да ли је овај приступ `пб` сигуран". Пошто је напорно сад ићи назад до онога ко позива ову функцију да се провери да ли је мутекс (монитор) закључан, боље је да се функцији просто проследи `тхумпер_индеџ`.

2019-11-07 13:29 UTC, Petar-Saric commented on core/pubnub_ccore_limits.h
> +#if !defined PUBNUB_MIN_TRANSACTION_TIMER
Treba mi za testove modula za tajmere.

2019-11-08 00:44 UTC, Petar-Saric commented on core/pubnub_ccore_limits.h
> +#if !defined PUBNUB_MIN_TRANSACTION_TIMER
Treba mi za testove modula za tajmere.

2019-11-10 10:47 UTC, sveljko requested changes

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    } autoRegister;
Ово се и даље зове "регистер".. управо, `аутоРегистер` је још апстрактније од само "регистер". Дај му неко мало прецизније име.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +/** Enables keeping presence on subscribed channels and channel groups.
ово јесте тачно, али, то је последица, а не оно што ради. Кад се описује функција, треба почети од онога што она ради.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    auto heartbeat is not disabled. This process is independent from anything user
боље `ис енаблед` него``ис нот дисаблед`.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    may by doing with the context when its not subscribing.
б_е_ доинг

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    If the uuid(or any other relevant data, like dns server, or proxy) is changed at
У коментарима, пасусе треба раздвојити празним редом.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    The same goes if the pubnub context leaves some of the channels, or channel groups.
хм, па, контекст никад не напушта канал... УУИД напушта канал.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    @param period_sec Auto heartbeat thumping period
напоменути у којим јединицима (да, `_сец` асоцира на то која је, али, треба бити изричит)

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    @param period_sec Auto heartbeat thumping period
као малопре

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +/** Desables auto heartbeat on the @p pb context.
д_и_саблес

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +/** Tells if auto heartbeat is enabled on the @p pb context.
Није то папагај па да прича. :)
Враћа.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +int pubnub_heartbeat_free_thumpers(void);
нисам анализирао код, али, начелно је уобичајено да `фрее` функције не враћају вредност. Наравно, има разлога да не буде тако, али, овде није јасно који су то разлози, нису објашњени нити је објашњено зашто ово може да не успе и шта да позивалац ради ако не успе.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +/** Commences auto heartbeat timer, if auto heartbeat is enabled and when subscribe transaction
Стартс

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +    is acomplished.
финисхед или доне - ацомплисх је неко достигнуће, нешто изузетно (попео се на врх планине).

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_auto_heartbeat.h
> +enum pubnub_res pbauto_heartbeat_form_channels_and_ch_groups(pubnub_t* pb,
хм, зар не рекосмо да се ова "двоглава аждаја" подели на две функције - једна која "снима" и друга која "чита"?

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +static int exclude_member(char** list, const char* member, size_t member_len)
колико ја видим, `лист` се у овој функцији увек користи само за читање (нигде нема `лист* = ….`), па нема потребе да буде `**`.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +    if (0 == list_len) {
мало је чудна спрега у којој се избацивање из празне ниске сматра грешком а неуспело избацивање из непразне ниске сматра успехом. Дакле, ако је услов за "испад из петље" функције која нас позива то да је "листа испражњена", онда нека се тиме бави та функција. Ова функција онда може да не враћа резултат или да врати `-1` за "нисам успео да избацим то што желиш (пошто га и нема)" и `0` за "избацио сам". Предлажем да не враћа ништа.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +            ((size_t)(list_ch_end - list_start) == member_len)) {
поређење величине је брже и стога треба да се ради прво. Ако се већ уради прво, онда знамо да су величине исте па можемо да искористимо бржи `мемцмп()`.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +                list_start[(list_start > *list) ? -1 : 0] = '\0';
треба избегавати гранања. Дакле, ово треба да буде:
* -1 ако је `лист_старт` веће од `*лист`
* 0 иначе

резултат поређења је 0 (нетачно) или 1 (тачно). 

на основу претходне две "изјаве", како би овај код преправио да нема услова?

Помоћ пријатеља: злоупотреби чудесну операцију "одузимања". :)

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +static void exclude_from_list(char** list, const char* leave_list)
ако ја добро видим, ова функција прима `**` за `лист` само зато што жели да ослободи меморију на коју `*лист` показује.

Међутим, то не би требало да ради (ако то није неопходно). Функција за избацивање из листе треба да, јелда, избацује из листе. ако некоме треба да, у неком случају, након тога и ослободи дотичну меморију, нека то уради сам.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +        return;
ако се избаци ослобађање меморије, онда ни овај "рани излазак" неће бити потребан, већ просто петља испод неће никад да се изврши.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +}
ова функција избацује само прво појављивање.  Дакле, ако имамо `а,б,а` а избацујемо `а`, добићемо `б,а`. Неко можда очекује да добије (само) `б`.

То је можда оно што желимо у нашем случај, али, ако јесте, треба то документовати.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +}
ову и претходну функцију треба извдојити у посебан модул, јер су прилично уопштене. Онда могу да имају и посебан тест модула. Тај модулу ставити у `либ` директоријум, јер нема везе са Ц-цоре-ом. Пошто ће да буду јавне функције прилично општог имена, дати им префикс `пб`, односно `пбстр`.

Сем тога, уместо `еџлуде` користи `ремове`, јер је то актив, а `еџлуде` се начелно односи на пасив.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +    }
хм, а шта ако је `цханнел==НУЛЛ` а `пб ауторегистер.цханнел != НУЛЛ`? Да можда не треба онда да се ослободи `ауторегистер.цханнел`?
и шта ако је обратно? зар онда не би требало да се уради `стрдуп()`?

Ако су дотичне ситуације "немогуће", додај АССЕРТ да се то "документује".

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_coreapi.c
> +    }
слично питање као малопре?

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    unsigned timer_index_array[PUBNUB_MAX_HEARTBEAT_THUMPERS] pubnub_guarded_by(timerlock);
није баш најјасније (може да се наслути) чему служи овај низ спрам оног пре њега. Треба документовати.

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +static void copy_context_settings(pubnub_t* pb_clone, pubnub_t* pb)
онај "са кога клонираш" треба да се прима са `пубнуб_т цонст*`

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        (pb_clone->core.subscribe_key != pb->core.subscribe_key)) {
а чему ово поређење? зашто увек просто не урадиш `пубнуб_инит()`?

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    snprintf(pb_clone->core.uuid, sizeof pb_clone->core.uuid, "%s", pb->core.uuid);
нема потребе за снпринтф(), ово су два иста поља. Можеш `стрцпу()` јер може да буде празно, као оптимизација да не користиш увек `мемцпу()`. Нема сврхе `стрнцпу()` јер ова поља морају да буду АСЦИИЗ ниске - ако нису, не мож ми ту много да помогнемо (а ако смо баш параноични, па можемо да видимо колико су дугачке па да "вичемо" ако су предугачке).

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +     */
овај коментар није користан.

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    snprintf(pb_clone->proxy_hostname, sizeof pb_clone->proxy_hostname, "%s", pb->proxy_hostname);
слично као малопре

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    snprintf(pb_clone->realm, sizeof pb_clone->realm, "%s", pb->realm);
слично као малопре

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    if (!pb_valid_ctx_ptr(pb)) {
ово је за АССЕРТ

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    return pb_clone;
хм, па ово није баш клон - има само исте кључеве, све остало је на подразумеваним вредностима, а не на онима из `пб`...

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    for (j = i; j < (*active_timers); j++) {
овде заграде нису потребне

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        indexes[j] = indexes[j+1];
ова петља може да се замени са једним `меммове()`

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +static int form_heartbeat_thumper(pubnub_t* pb)
на основу имена и кода, није баш најјаснија сврха ове функције, треба документовати (да не мора човек да тражи одакле се зове да би закључио чему служи)

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        if (form_heartbeat_thumper(pb) != 0) {
хм, ако добро разумем, ово ће да "омогући" Тупка ако већ није омогућен? Али, то не желимо. Ако Тупко није већ омогућен, ово треба да врати грешку.

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        : period_sec;
ово је одвећ дугачак ред за просту ствар. Уведи помоћну константу за `ПУНБУНБ_МИН... / УНИТ_ИН_МИЛЛИ`.

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +            return 0;
овде просто уради `бреак` и онда не мораш да откључаваш мутекс, то ће  и тако да се уради кад се изађе из петље. Резултат ти, колико видим не треба, јер га нико не користи.

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    if (thumper_index < PUBNUB_MAX_HEARTBEAT_THUMPERS) {
ово треба у АССЕРТ

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        case PBTT_SUBSCRIBE_V2 :
хм, а шта ако корисник уради ХЕАРТБЕАТ? Што и ми то да радимо и "дуплирамо посао"?

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +static void pause_auto_heartbeat(unsigned thumper_index)
хм, није јасно по чему је ово другачије од `стоп_хеартбеат`, односно, што је ово `паусе`?

2019-11-10 10:47 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +        default:
слично као малопре, обрада би требала да буде иста за претплату и `хеартбеат` који је урадио корисник.

2019-11-10 10:47 UTC, sveljko commented on core/pubnub_netcore.c
> +        pbauto_heartbeat_notify(pb);
треба јој дати описније име од `нотифу`.

2019-11-12 15:26 UTC, sveljko requested changes

2019-11-12 15:26 UTC, sveljko commented on lib/pbstr_remove_from_list.h
> +    Liberates memory if list string is empty.
frees memory (liberates је ослобађање нечег што је окупирано, заробљено, а не што је просто заузето)

2019-11-12 15:26 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    PUBNUB_ASSERT_OPT(m_watcher.active_timers < PUBNUB_MAX_HEARTBEAT_THUMPERS);
хм, дакле, ти мислиш да у "регуларном" раду не може да дође до тога да `ацтиве_тимер` пређе границу? Звучи логично, али, јел смо сигурни у то?

2019-11-12 15:26 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +static bool is_excepted(pubnub_t const* pb, unsigned thumper_index)
ваљда `еџпецтед` (очекивани)?

2019-11-12 15:26 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +static void init_and_thump_again_if_keys_were_changed(pubnub_t* heartbeat_pb, pubnub_t* pb)
колико ја видим, ово се позива на само једном месту, а прилично је "рогобатно" име и очигледно функција која "условно" нешто ради. Најљепше је кад сваки функција увек ради једно те исто (евентуално одрађујући то исто под различитим условима окружења). Такође, ова функција је умерено кратка. Стога, мислим да је најбоље да се ово парче кода просто премести "на место позива" и функција као таква избаци.

2019-11-12 15:26 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +            /* Depending on kind of error try thumping again */
Депендинг он _тхе_ кинд оф еррор _,_ тру тхумпинг агаин

2019-11-12 16:06 UTC, Petar-Saric commented on posix/pbauto_heartbeat_callback_posix.c
> +    PUBNUB_ASSERT_OPT(m_watcher.active_timers < PUBNUB_MAX_HEARTBEAT_THUMPERS);
Da smo bash sto posto sigurni ne bi stojao assert.

2019-11-12 16:11 UTC, Petar-Saric commented on posix/pbauto_heartbeat_callback_posix.c
> +static bool is_excepted(pubnub_t const* pb, unsigned thumper_index)
Не очекивани него изузет из подразумеване обраде.

2019-11-12 20:10 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +static bool is_excepted(pubnub_t const* pb, unsigned thumper_index)
Онда нека буде еџемптед, то је прецизнији превод и мања шанса да га неко побрка са еџпецтед.

2019-11-12 20:18 UTC, sveljko commented on posix/pbauto_heartbeat_callback_posix.c
> +    PUBNUB_ASSERT_OPT(m_watcher.active_timers < PUBNUB_MAX_HEARTBEAT_THUMPERS);
АССЕРТ (треба да) стоји за "нерегуларни" рад, да се ухвати нешто што "не би смело да се деси" (дакле, нека буба). 

Рецимо, на крају функције за уређивање низа може под АССЕРТ-ом да стоји провера да ли је низ уређен. У самој функцији, може да стоји провера неког индекса (јер свакако да постоји неки индекс), прецизније да ли је у опсегу (димензије низа који уређује). Међутим, неки алгоритам може да буде такав да управо дозвољава да индекс некад изађе из опсега (али никад га не користи за приступ низу када је ван опсега) и онда нема смисла да се то АССЕРТ-ује. С друге стране, неки други алгоритам управо треба да буде такав да индекс не сме да изађе из опсега и онда то управо _треба_ да се АССЕРТ-ује.

Другим речима, питање је: у одсуству буба, да ли некако може да се деси да овде `ацтиве_тимерс` не буде у опсегу? Ако не може, онда је АССЕРТ у реду. Ако ипак може, онда треба "пуноправна обрада" (мада, за сврхе дебубовања, може да да остане _и_ АССЕРТ)

2019-11-12 21:12 UTC, Petar-Saric commented on posix/pbauto_heartbeat_callback_posix.c
> +    PUBNUB_ASSERT_OPT(m_watcher.active_timers < PUBNUB_MAX_HEARTBEAT_THUMPERS);
Очекивао сам тако сажет одговор одговора и да у одсуству буба број активних тајмера не може бити већи од броја тупко-контекста који их користе.

2019-11-14 13:31 UTC, merged