Develop
gvs-rs/pubnub-c-core pull request #35
Opened 2019-11-24 00:10 UTC by Petar-Saric

Тупко #29 : sync

2019-11-24 20:15 UTC, sveljko requested changes

2019-11-24 20:15 UTC, sveljko commented on cpp/fntest/pubnub_fntest_medium.cpp
> +//    SENSE(pbp.subscribe("")).in(Td) == PNR_INVALID_CHANNEL;
Што је ово закоментарисано?

2019-11-24 20:15 UTC, sveljko commented on core/pb_sleep_ms.h
> +#include <windows.h>
Мало је "превише" да свако ко хоће ово да користи укључи цео Њиндоњс.Х који је _огроман_. Дакле, овде онда немој да користиш `ДЊОРД` тип, већ просто увек користи `унсигнед лонг`.

2019-11-24 20:15 UTC, sveljko commented on core/fntest/pubnub_fntest_medium.c
> +//    expect_pnr(pubnub_subscribe(pbp, NULL, NULL), PNR_INVALID_CHANNEL);
Што је ово закоментарисано?

2019-11-24 20:15 UTC, sveljko commented on core/pbauto_heartbeat.c
> -    pb_clone->options.use_blocking_io = pb->options.use_blocking_io;
што се ово више "не клонира"?

2019-11-24 20:15 UTC, sveljko commented on core/pbauto_heartbeat.h
> +    /** Used in sync environment. */
добро, лепо је знати када се користи (мада се то да закључити на основу `иф !дефинед` изнад), али а _шта_ представља?

2019-11-24 20:15 UTC, sveljko commented on core/pbauto_heartbeat.h
> +    /** Array of thumper indexes whos auto heartbeat transactions are currently in progress.
"who's" се у енглеском више користи за бића. За појмове, користиш `фор њхицх`, или тако нешто.

Узгред, у техничким текстовима, уобичајеније је да се користи `индицес` за множину од `индеџ`, јер је тако у изворном Латинском, а коментар кода је технички текст (наспрам коментара јавне функције, који баш и није).

2019-11-24 21:25 UTC, Petar-Saric commented on cpp/fntest/pubnub_fntest_medium.cpp
> +//    SENSE(pbp.subscribe("")).in(Td) == PNR_INVALID_CHANNEL;
Pogadjaj.

2019-11-24 21:50 UTC, Petar-Saric commented on core/fntest/pubnub_fntest_medium.c
> +//    expect_pnr(pubnub_subscribe(pbp, NULL, NULL), PNR_INVALID_CHANNEL);
Два НУЛЛа више нису недозвољена када је 'тупко' укључен. Закоментарисани су они делови на којима функцонални тестови сада падају(уместо недозвољених параметара пријављују започету трансакцију) јер као и примери укључују све модуле. То, за сада, не важи за тестове модула.

2019-11-24 21:57 UTC, Petar-Saric commented on core/pbauto_heartbeat.c
> -    pb_clone->options.use_blocking_io = pb->options.use_blocking_io;
Предвиђено понашање 'тупко' модула је неблокирајући ио осим, ако немамо другог избора осим подразумеваног.

2019-11-25 19:18 UTC, sveljko commented on core/fntest/pubnub_fntest_medium.c
> +//    expect_pnr(pubnub_subscribe(pbp, NULL, NULL), PNR_INVALID_CHANNEL);
Па, добро, али, ми знамо када је Тупко укључен, зар не? Тури онда ово под одговарајући `#иф дефинед`

2019-11-25 19:19 UTC, sveljko commented on cpp/fntest/pubnub_fntest_medium.cpp
> +//    SENSE(pbp.subscribe("")).in(Td) == PNR_INVALID_CHANNEL;
Због ДНК и протеина?

2019-11-25 19:21 UTC, sveljko requested changes

2019-11-25 19:21 UTC, sveljko commented on core/pb_sleep_ms.h
>  void pb_sleep_ms(long milliseconds);
нема потребе за `#иф дефинед`, нека буде _увек_ унсигнед лонг (или "означени" `лонг`, ако ти се тако више свиђа, није много важно, сигурно нећемо овако да спавамо милионима милисекунди

2019-12-01 14:03 UTC, merged